language: ruby
cache: bundler
rvm: 2.6

before_script:
  - chmod a+x _site/script/bootstrap
  - chmod a+x _site/script/cibuild
  - chmod a+x _site/script/rebund
  - chmod a+x _site/script/release
install: script/bootstrap
script: script/cibuild
